#
# Makefile for gptsync on Unix platforms
#

RM = rm -f
CC = gcc

OBJS   = gptsync.o os_unix.o

TARGET = gptsync

CPPFLAGS = -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I../include
CFLAGS   = -Wall
LDFLAGS  =
LIBS     =

# system-dependent additions

system = $(shell uname)
ifeq ($(system),Darwin)
  CC        = gcc-4.0
  CFLAGS   += -arch i386 -arch ppc
  LDFLAGS  += -arch i386 -arch ppc
  ifeq (/Developer/SDKs/MacOSX10.4u.sdk,$(wildcard /Developer/SDKs/MacOSX10.4u.sdk))
    CPPFLAGS += -isysroot /Developer/SDKs/MacOSX10.4u.sdk
    LDFLAGS  += -Wl,-syslibroot,/Developer/SDKs/MacOSX10.4u.sdk
  endif
endif

# real making

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS) $(LIBS)

$(OBJS): %.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $<

# cleanup

clean:
	$(RM) *.o *~ *% $(TARGET)

distclean: clean
	$(RM) .depend

# automatic dependencies

depend: dep
dep:
	for i in $(OBJS:.o=.c) ; do $(CC) $(CPPFLAGS) -MM $$i ; done > .depend

ifeq (.depend,$(wildcard .depend))
include .depend
endif

# eof
