#
# Makefile for efilipo on Unix platforms
#

RM = rm -f
CC = gcc

TARGET = efilipo
OBJS   = efilipo.o

CPPFLAGS = -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
CFLAGS   = -Wall
LDFLAGS  =
LIBS     =

# real making

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

efilipo.o: efilipo.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

# cleanup

clean:
	$(RM) *.o *~ *% $(TARGET)

distclean: clean
	$(RM) .depend

# eof
